[package]
name = "undetectableGPT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5"

[[bin]]
name = "undetectableGPT"
path = "main.rs"
